### ISSUE TITLE
error in Fingerprints to Spritesheet nb

### ISSUE THREAD

**Issue by EMCP** [kylemcdonald/AudioNotebooks#5]
noticed a variable that was never defined inside `Fingerprints to Spritesheet.ipynb`

![screen shot 2017-06-22 at 12 29 26 am](https://user-images.githubusercontent.com/3691722/27422104-df10a792-56e1-11e7-9155-b740e419db01.png)

I'm thinking this needs to point to... the `tsne/` fingerprints folder? not `grid/`?  and `p` should be the perplexity?  or are you just loading the single `fingerprints.npy` numpy file ?

![screen shot 2017-06-22 at 12 33 17 am](https://user-images.githubusercontent.com/3691722/27422288-682ce7ca-56e2-11e7-8019-bd5256046d30.png)

Edit : Ah, now I see you mention a cloud grid at the top of the NB.. not clear which other NB that's referring to, but I'll look around

got it : https://github.com/kylemcdonald/CloudToGrid/

**Comment by EMCP** [comment]
@kylemcdonald would be great if you could confirm my assumptions on these files

**Comment by kylemcdonald** [comment]
everything you figured out was 100% correct. if you want to contribute your notes to the notebooks that would be very welcome. thanks!
