### ISSUE TITLE
what version of bh_tsne did you compile?

### ISSUE THREAD

**Issue by mattetti** [kylemcdonald/AudioNotebooks#6]
When running the Fingerprints to t-SNE notebook on Linux I get a major crash because bh_tsne is a macho binary which makes sense. However when I try to swap the binary by a compiled version for linux I get an error with exit code -11:

```
ERROR: Call to bh_tsne exited with a non-zero return code exit status, please refer to the bh_tsne output for further details
```

I tried a few versions of the library, including https://github.com/kylemcdonald/bhtsne but I don't seem to have the right version (or there is another issue). @kylemcdonald any pointers would be very much appreciated!

**Comment by mattetti** [comment]
I assume this is it: https://github.com/ninjin/barnes-hut-sne

**Comment by EMCP** [comment]
Might try this one https://github.com/lvdmaaten/bhtsne

I used the updated wrapper to get this all working in Py3

**Comment by kylemcdonald** [comment]
yes, it's https://github.com/lvdmaaten/bhtsne
