### ISSUE TITLE
list_all_files

### ISSUE THREAD

**Issue by puterd** [kylemcdonald/AudioNotebooks#8]
I've got the audio notebook running but getting:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-0e881602a464> in <module>()
      1 import numpy as np
      2 from os.path import join
----> 3 from utils import *
      4 from multiprocessing import Pool

~/AudioNotebooks/utils/__init__.py in <module>()
----> 1 from list_all_files import list_all_files
      2 from ffmpeg_load_audio import ffmpeg_load_audio
      3 from ffmpeg_save_audio import ffmpeg_save_audio
      4 from show_array import show_array
      5 from make_mosaic import make_mosaic

ModuleNotFoundError: No module named 'list_all_files'

in collect samples. I'm new to Python so could be something very simple. Thanks!

**Comment by peterViou** [comment]
Hi, I have the same issue : can you explain to me how do you resolve it ?

**Comment by mihnagy** [comment]
The same here, how you solved it?

**Comment by kylemcdonald** [comment]
https://github.com/kylemcdonald/python-utils/blob/master/list_all_files.py
